# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c4a3160c958784637bb1fbe9d311e63446744148c4302784c3d1ec73ff9b4aad825c57adf0aa2a3f5c5095eb4ab6ee1257f11d070399d6f8eec35aeaa00d514

test:
  secret_key_base: e23a761dbcd7de4d1f4a431f9c71b4d99af8ff404b10fed39575f3e1143a39a2109be70b2d7c8e0e8630d00804476db885e63a55c670b7b0771d835b3281f449

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
